# Generated by Django 4.1 on 2022-10-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
