# Generated by Django 4.1 on 2022-10-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0002_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
    ]
