# Generated by Django 4.1 on 2022-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0003_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='asd', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
