# Generated by Django 4.1 on 2022-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0005_nullblankdemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='nullblankdemo',
            name='blank',
        ),
        migrations.RemoveField(
            model_name='nullblankdemo',
            name='null',
        ),
    ]
