# Generated by Django 4.1 on 2022-10-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0006_department_remove_nullblankdemo_blank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models_exercise.department'),
            preserve_default=False,
        ),
    ]
