# Generated by Django 4.1 on 2022-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0008_project_employee_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(related_name='employees', to='models_exercise.project'),
        ),
    ]
