# Generated by Django 4.1 on 2022-10-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0009_alter_employee_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models_exercise.employee')),
            ],
        ),
    ]
