# Generated by Django 4.1 on 2022-10-09 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0010_accesscard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscard',
            name='id',
        ),
        migrations.AlterField(
            model_name='accesscard',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models_exercise.employee'),
        ),
    ]
