# Generated by Django 4.1 on 2022-10-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0011_remove_accesscard_id_alter_accesscard_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NullBlankDemo',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-age',)},
        ),
    ]
