# Generated by Django 4.1 on 2022-10-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_exercise', '0013_department_created_on_department_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
