# Generated by Django 4.1 on 2022-10-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_album_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.profile'),
        ),
    ]
