# Generated by Django 4.1 on 2022-10-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_album_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='owned',
        ),
        migrations.AddField(
            model_name='album',
            name='owned',
            field=models.ManyToManyField(to='web.profile'),
        ),
    ]
